title: CPOL Cookbook
author: LAGER Development Team
logo: images/argonne-logo.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - html_image
html:
  comments:
    hypothesis: true
repository:
  url: https://github.com/LAGER/SAILS-radar-analysis  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  jupyterhub_url: "https://jupyter.alcf.anl.gov/theta"